import { Product, Shop, Review, Order } from '@/app/lib/types';
import { PlaceHolderImages } from './placeholder-images';

/**
 * @fileOverview Mock Database for LocaleConnect Prototyping.
 * In a production app, this would be replaced by Firestore or a SQL DB.
 */

export let shops: Shop[] = [
  {
    id: 's1',
    vendorId: 'v1',
    name: "Bloom Bakery",
    type: "Bakery",
    description: "Artisan sourdough and neighborhood favorites baked fresh daily using locally sourced organic ingredients.",
    location: "123 Maple St, Old Town",
    hours: "8 AM - 6 PM",
    rating: 4.8,
    imageUrl: PlaceHolderImages.find(img => img.id === 'bakery-shop')?.imageUrl || "",
    createdAt: new Date(),
  },
  {
    id: 's2',
    vendorId: 'v2',
    name: "The Velvet Hanger",
    type: "Boutique",
    description: "Curated vintage finds and modern sustainable fashion for the conscious shopper.",
    location: "456 Oak Avenue",
    hours: "10 AM - 8 PM",
    rating: 4.9,
    imageUrl: PlaceHolderImages.find(img => img.id === 'boutique-shop')?.imageUrl || "",
    createdAt: new Date(),
  },
  {
    id: 's3',
    vendorId: 'v3',
    name: "Steam & Bean",
    type: "Cafe",
    description: "Your local destination for specialty coffee and community vibes. We roast our own beans weekly.",
    location: "789 Pine Lane",
    hours: "7 AM - 5 PM",
    rating: 4.7,
    imageUrl: PlaceHolderImages.find(img => img.id === 'cafe-shop')?.imageUrl || "",
    createdAt: new Date(),
  },
  {
    id: 's4',
    vendorId: 'v4',
    name: "Clay Creations",
    type: "Pottery",
    description: "Handcrafted ceramics made right here in the neighborhood. Unique pieces for your home.",
    location: "101 River Road",
    hours: "11 AM - 4 PM",
    rating: 5.0,
    imageUrl: PlaceHolderImages.find(img => img.id === 'product-mug')?.imageUrl || "",
    createdAt: new Date(),
  }
];

export let products: Product[] = [
  {
    id: 'p1',
    shopId: 's4',
    name: "Handcrafted Ceramic Mug",
    description: "A beautiful, hand-thrown ceramic mug with a unique glaze finish. Perfect for your morning coffee or tea. Each piece is unique due to the artisanal firing process.",
    price: 240.00,
    category: "Home",
    imageUrl: PlaceHolderImages.find(img => img.id === 'product-mug')?.imageUrl || "",
    stockQuantity: 12,
    isActive: true,
    rating: 4.9,
    createdAt: new Date(),
  },
  {
    id: 'p2',
    shopId: 's1',
    name: "Wildflower Honey",
    description: "Pure, raw honey collected from local wildflowers. Our honey is never pasteurized, preserving all the natural enzymes and local pollen benefits.",
    price: 125.50,
    category: "Food",
    imageUrl: PlaceHolderImages.find(img => img.id === 'product-honey')?.imageUrl || "",
    stockQuantity: 25,
    isActive: true,
    rating: 4.7,
    createdAt: new Date(),
  },
  {
    id: 'p3',
    shopId: 's3',
    name: "Artisan Coffee Blend",
    description: "Our signature medium roast blend with notes of chocolate and citrus. Beans are sourced ethically and roasted in small batches right here in town.",
    price: 180.00,
    category: "Food",
    imageUrl: PlaceHolderImages.find(img => img.id === 'product-coffee')?.imageUrl || "",
    stockQuantity: 40,
    isActive: true,
    rating: 4.8,
    createdAt: new Date(),
  },
  {
    id: 'p4',
    shopId: 's1',
    name: "Sourdough Bread",
    description: "Naturally leavened bread with a crisp crust and airy interior. Made with a 50-year-old starter and high-quality organic flour.",
    price: 80.00,
    category: "Food",
    imageUrl: PlaceHolderImages.find(img => img.id === 'product-bread')?.imageUrl || "",
    stockQuantity: 10,
    isActive: true,
    rating: 4.9,
    createdAt: new Date(),
  },
  {
    id: 'p5',
    shopId: 's2',
    name: "Vintage Denim Jacket",
    description: "Classic vintage denim jacket, hand-selected for quality. A timeless piece that only gets better with age. Authentic distressing and heavy-duty hardware.",
    price: 650.00,
    category: "Clothing",
    imageUrl: PlaceHolderImages.find(img => img.id === 'product-jacket')?.imageUrl || "",
    stockQuantity: 1,
    isActive: true,
    rating: 4.6,
    createdAt: new Date(),
  },
  {
    id: 'p6',
    shopId: 's3',
    name: "Sea Salt & Orchid Candle",
    description: "Hand-poured soy candle with a refreshing coastal scent. Lead-free cotton wicks and phthalate-free fragrance oils for a clean burn.",
    price: 320.00,
    discountPrice: 280.00,
    category: "Home",
    imageUrl: PlaceHolderImages.find(img => img.id === 'product-candle')?.imageUrl || "",
    stockQuantity: 15,
    isActive: true,
    rating: 4.5,
    createdAt: new Date(),
  },
  {
    id: 'p7',
    shopId: 's4',
    name: "Organic Goat Milk Soap",
    description: "Gentle, moisturizing soap made with natural oils and fresh goat milk from local farms. Great for sensitive skin and daily use.",
    price: 110.00,
    category: "Home",
    imageUrl: PlaceHolderImages.find(img => img.id === 'product-soap')?.imageUrl || "",
    stockQuantity: 30,
    isActive: true,
    rating: 4.8,
    createdAt: new Date(),
  },
  {
    id: 'p8',
    shopId: 's2',
    name: "Canvas Market Tote",
    description: "Durable, hand-painted tote bag perfect for neighborhood shopping. Reinforced handles and heavy-weight organic canvas.",
    price: 150.00,
    category: "Clothing",
    imageUrl: PlaceHolderImages.find(img => img.id === 'product-tote')?.imageUrl || "",
    stockQuantity: 20,
    isActive: true,
    rating: 4.7,
    createdAt: new Date(),
  },
  {
    id: 'p9',
    shopId: 's4',
    name: "Hand-carved Salad Servers",
    description: "Unique salad servers carved from reclaimed mango wood. Treated with food-safe oils to highlight the natural wood grain.",
    price: 450.00,
    discountPrice: 399.00,
    category: "Home",
    imageUrl: PlaceHolderImages.find(img => img.id === 'product-spoon')?.imageUrl || "",
    stockQuantity: 8,
    isActive: true,
    rating: 5.0,
    createdAt: new Date(),
  },
  {
    id: 'p10',
    shopId: 's2',
    name: "Hand-knitted Alpaca Scarf",
    description: "Luxuriously soft scarf knitted by local artisans using pure alpaca wool. Incredibly warm and hypoallergenic.",
    price: 850.00,
    category: "Clothing",
    imageUrl: PlaceHolderImages.find(img => img.id === 'product-scarf')?.imageUrl || "",
    stockQuantity: 5,
    isActive: true,
    rating: 4.9,
    createdAt: new Date(),
  }
];

export let reviews: Review[] = [
  { id: 'r1', customerId: 'c1', shopId: 's4', rating: 5, comment: "Absolutely love the texture of this mug! It holds heat really well.", createdAt: new Date() },
  { id: 'r2', customerId: 'c2', shopId: 's4', rating: 4, comment: "Beautiful design, though a bit heavier than I expected.", createdAt: new Date() },
  { id: 'r3', customerId: 'c3', shopId: 's1', rating: 5, comment: "Best sourdough in the neighborhood. Still fresh after 3 days!", createdAt: new Date() },
  { id: 'r4', customerId: 'c4', shopId: 's3', rating: 5, comment: "The orchid scent is divine and not overpowering at all.", createdAt: new Date() },
];

export let orders: Order[] = [
  {
    id: 'ord1',
    customerId: 'user123',
    shopId: 's1',
    status: 'completed',
    totalAmount: 160.00,
    items: [
      { productId: 'p4', name: 'Sourdough Bread', price: 80.00, quantity: 2 }
    ],
    createdAt: new Date(Date.now() - 86400000 * 5)
  },
  {
    id: 'ord2',
    customerId: 'user123',
    shopId: 's4',
    status: 'processing',
    totalAmount: 255.00,
    items: [
      { productId: 'p1', name: 'Handcrafted Ceramic Mug', price: 240.00, quantity: 1 }
    ],
    createdAt: new Date()
  }
];
